### ISSUE TITLE
library error

### ISSUE THREAD

**Issue by jperry82** [Vae2009/ConRO#1]
Good morning,

I am getting the below error on all of my toons. I have attempted to delete and reinstall Conro with no success. I also deleted associated files from my WTF folder and still no improvement on the issue. Any help that you can provide would be greatly appreciated.

Message: Interface/AddOns/ConRO/buttons.lua:1822: Cannot find a library instance of "LibCustomGlow-1.0".
Time: Sun Nov 27 07:34:43 2022
Count: 1
Stack: Interface/AddOns/ConRO/buttons.lua:1822: Cannot find a library instance of "LibCustomGlow-1.0".
[string "=(tail call)"]: ?
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibStub/LibStub.lua"]:38: in function `GetLibrary'
[string "@Interface/AddOns/ConRO/buttons.lua"]:1822: in function `UpdateButtonGlow'
[string "@Interface/AddOns/ConRO/core.lua"]:2305: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:117: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:117>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:27: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:23>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:62: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Vae2009** [comment]
This is an issue with ElvUI libraries.
