### ISSUE TITLE
Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID) error when enterin raid instance.

### ISSUE THREAD

**Issue by Ookami313** [Vae2009/ConRO#10]
Entered the new wing of LFR and received the following error. Thanks.

8x Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
[string "=[C]"]: in function `GetLastSelectedSavedConfigID'
[string "@ConRO/helper.lua"]:22: in function `CheckTalents'
[string "@ConRO/core.lua"]:2031: in function `EnableRotation'
[string "@ConRO/core.lua"]:2346: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by Vae2009** [comment]
Yes, I am finding errors like this I am trying to find a solution.
