### ISSUE TITLE
LUA Error on exit from Arena Skirmish

### ISSUE THREAD

**Issue by squish88** [Vae2009/ConRO#11]
I've removed several add-ons and the only consistent mod mentioned is this one.  The below LUA pops up whenever I exit from an Arena Skirmish back into Valdrakken.

Message: Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
Time: Sat Jan  7 17:39:37 2023
Count: 1
Stack: Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
[string "=[C]"]: in function `GetLastSelectedSavedConfigID'
[string "@Interface/AddOns/ConRO/helper.lua"]:22: in function `CheckTalents'
[string "@Interface/AddOns/ConRO/core.lua"]:2031: in function `EnableRotation'
[string "@Interface/AddOns/ConRO/core.lua"]:2346: in function `?'
[string "@Interface/AddOns/Capping/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ing/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Capping/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ing/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Capping/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Vae2009** [comment]
Common error I am trying to find a fix for.
