### ISSUE TITLE
Error in 10.0.31

### ISSUE THREAD

**Issue by solitha** [Vae2009/ConRO#18]
Told you I'd give it a workout :) On first entering combat after a talent change. Frost mage lvl 37 BAEAHVkVsxxZrVqBmAzlSR2f7LAAASRgDQiIiIBAAAAAkASKJJJCAAAAAAAAAgA

`1x [ADDON_ACTION_BLOCKED] AddOn 'ConRO' tried to call the protected function 'ActionButton2:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:342: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:801: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:196: in function <FrameXML/ActionButton.lua:193>`

**Comment by Vae2009** [comment]
Ya, this protected function is one of blizzard taints.
