### ISSUE TITLE
Hunter ConRO does not recognize Mongoose Bite

### ISSUE THREAD

**Issue by Roweson** [Vae2009/ConRO#3]
Hello, 

Used it the addon today and kept getting errors for not having 'Raptor Strike' on Surv build, which uses 'Mongoose Bite' as the talent replacement.   I am following the method.gg/guides/survival-hunter/talents AoE build a link of the talents here https://www.wowhead.com/talent-calc/hunter/survival/DAOBJEVVYFEGCgkFQCRQMWVFEVlKgRCgEBQ

**Comment by Vae2009** [comment]
Fixed and uploaded.
