### ISSUE TITLE
Frost DK not showing DPS abilities.

### ISSUE THREAD

**Issue by JakobSvahn** [Vae2009/ConRO#6]
Suddenly in the start of a dungeon it just stopped showing what abilities it wants me to use. it works for every other character i have and even works on Blood and Unholy DK aswell. I've tried reinstalling the addon completely and tried resetting all the settings many times. I dont know what to do now.

**Comment by Vae2009** [comment]
Can you share your talent link please.

**Comment by JakobSvahn** [comment]
> Can you share your talent link please.

BsPAdLUHklrTr3hBIcYWdbnCGnkEgkEJJiIEBhkkIcgIJRSIJBISiEJJJJpAAAAAAAAAAAAAA

**Comment by Vae2009** [comment]
Try out ConRO v10.0.21 please. I may have found the fix.
