### ISSUE TITLE
local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)

### ISSUE THREAD

**Issue by Ookami313** [Vae2009/ConRO#8]
Joined an Alterac Valley BG on my Horde Evoker (61) to work on holiday achievements and started getting the following error. Thanks.

3x Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
[string "=[C]"]: in function `GetLastSelectedSavedConfigID'
[string "@ConRO/helper.lua"]:21: in function `CheckTalents'
[string "@ConRO/core.lua"]:2031: in function `EnableRotation'
[string "@ConRO/core.lua"]:2321: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by Vae2009** [comment]
Try out ConRO v10.0.21 please. I may have found the fix.
