### ISSUE TITLE
Feral Druid Errors

### ISSUE THREAD

**Issue by stydermmb** [Vae2009/ConRO#9]
Talent Code: BcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIFkIJJRSJtDIKJJxBSCAAAAAAKgAQikkkIJ5AhkQLB4AAAAAAAAA

As a feral druid, ConRo works fine in Cat Form, but on shifting to Bear Form it throws 2 errors:

Message: Interface/AddOns/ConRO_Druid/druid.lua:581: attempt to compare nil with number
Time: Wed Dec 21 00:20:29 2022
Count: 12
Stack: Interface/AddOns/ConRO_Druid/druid.lua:581: attempt to compare nil with number
[string "@Interface/AddOns/ConRO_Druid/druid.lua"]:581: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2433: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: _ = <table> {
 AbilityPurge = <function> defined @Interface/AddOns/ConRO/buttons.lua:2763
 IsPvP = <function> defined @Interface/AddOns/ConRO/helper.lua:50
 Dragonriding = <function> defined @Interface/AddOns/ConRO/helper.lua:1131
 DestroyPurgableOverlays = <function> defined @Interface/AddOns/ConRO/buttons.lua:1684
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 AbilityInterrupt = <function> defined @Interface/AddOns/ConRO/buttons.lua:2723
 ItemEquipped = <function> defined @Interface/AddOns/ConRO/helper.lua:147
 PurgeWindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:1047
 InterruptGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1847
 ScheduleTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @Interface/AddOns/ConRO/helper.lua:69
 CreateDefenseOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1254
 Heroism = <function> defined @Interface/AddOns/ConRO/helper.lua:434
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @Interface/AddOns/ConRO/core.lua:2467
 ClearAbilityRaidBuffsIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2692
 CreateRaidBuffsOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1518
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @Interface/AddOns/ConRO/helper.lua:365
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/ConRO/core.lua:2253
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <function> defined @Interface/AddOns/ConRO/core.lua:2408
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1188
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @Interface/AddOns/ConRO/helper.lua:856
 Dump = <function> defined @Interface/AddOns/ConRO/buttons.lua:2600
 Colors = <table> {
 }
 RaidBuff = <function> defined @Interface/AddOns/ConRO/helper.lua:522
 ClearAbilityInterruptIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2668
 ToggleDamage = <function> defined @Interface/AddOns/ConRO/buttons.lua:718
 Disable = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @Interface/AddOns/ConRO/core.lua:2309
 Print = <function> defined @Interface/AddOns/ConRO/core.lua:2017
 BurstMode = <function> defined @Interface/AddOns/ConRO/helper.lua:81
 LEARNED_SPELL_IN_TAB = <function> defined @Interface/AddOns/ConRO/core.lua:2408
 HideTauntGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1955
 DefFetchDiabolic = <function> defined @Interface/AddOns/ConRO/buttons.lua:2510
 CreateBurstButton = <function> defined @Interface/AddOns/ConRO/buttons.lua:483
 Totem = <function> defined @Interface/AddOns/ConRO/helper.lua:1119
 SlashUnlock = <function> defined @Interface/AddOns/ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @Interface/AddOns/ConRO/helper.lua:943
 EnableModule = <function> def

----------------------------------------------------------and Error 2------------------------------------------------------------- 

Message: Interface/AddOns/ConRO_Druid/druid.lua:581: attempt to compare nil with number
Time: Wed Dec 21 00:20:28 2022
Count: 6
Stack: Interface/AddOns/ConRO_Druid/druid.lua:581: attempt to compare nil with number
[string "@Interface/AddOns/ConRO_Druid/druid.lua"]:581: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2433: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConRO/buttons.lua"]:2158: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: _ = <table> {
 AbilityPurge = <function> defined @Interface/AddOns/ConRO/buttons.lua:2763
 IsPvP = <function> defined @Interface/AddOns/ConRO/helper.lua:50
 Dragonriding = <function> defined @Interface/AddOns/ConRO/helper.lua:1131
 DestroyPurgableOverlays = <function> defined @Interface/AddOns/ConRO/buttons.lua:1684
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 AbilityInterrupt = <function> defined @Interface/AddOns/ConRO/buttons.lua:2723
 ItemEquipped = <function> defined @Interface/AddOns/ConRO/helper.lua:147
 PurgeWindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:1047
 InterruptGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1847
 ScheduleTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @Interface/AddOns/ConRO/helper.lua:69
 CreateDefenseOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1254
 Heroism = <function> defined @Interface/AddOns/ConRO/helper.lua:434
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @Interface/AddOns/ConRO/core.lua:2467
 ClearAbilityRaidBuffsIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2692
 CreateRaidBuffsOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1518
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @Interface/AddOns/ConRO/helper.lua:365
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/ConRO/core.lua:2253
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <function> defined @Interface/AddOns/ConRO/core.lua:2408
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1188
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @Interface/AddOns/ConRO/helper.lua:856
 Dump = <function> defined @Interface/AddOns/ConRO/buttons.lua:2600
 Colors = <table> {
 }
 RaidBuff = <function> defined @Interface/AddOns/ConRO/helper.lua:522
 ClearAbilityInterruptIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2668
 ToggleDamage = <function> defined @Interface/AddOns/ConRO/buttons.lua:718
 Disable = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @Interface/AddOns/ConRO/core.lua:2309
 Print = <function> defined @Interface/AddOns/ConRO/core.lua:2017
 BurstMode = <function> defined @Interface/AddOns/ConRO/helper.lua:81
 LEARNED_SPELL_IN_TAB = <function> defined @Interface/AddOns/ConRO/core.lua:2408
 HideTauntGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1955
 DefFetchDiabolic = <function> defined @Interface/AddOns/ConRO/buttons.lua:2510
 CreateBurstButton = <function> defined @Interface/AddOns/ConRO/buttons.lua:483
 Totem = <function> defined @Interface/AddOns/ConRO/helper.lua:1119
 SlashUnlock = <function> defined @Interface/AddOns/ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/ConRO/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <funct

**Comment by Vae2009** [comment]
Found the issue, and fixed in next update v10.0.7
